//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterFloor.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address
    {
        public Address()
        {
            this.Partners = new HashSet<Partners>();
        }
    
        public int Id { get; set; }
        public string PostNumber { get; set; }
        public string RegionName { get; set; }
        public string CityName { get; set; }
        public string StreetName { get; set; }
        public int HomeNumber { get; set; }
    
        public virtual ICollection<Partners> Partners { get; set; }
    }
}
