//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterFloor.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Partners
    {
        public Partners()
        {
            this.PartnerProduct = new HashSet<PartnerProduct>();
        }
    
        public int Id { get; set; }
        public int PartnerTypeId { get; set; }
        public string Name { get; set; }
        public int DirectorId { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public int AddressId { get; set; }
        public string INN { get; set; }
        public int Rating { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual ICollection<PartnerProduct> PartnerProduct { get; set; }
        public virtual PartnerType PartnerType { get; set; }
        public virtual Person Person { get; set; }
    }
}
