//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterFloor.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.PartnerProduct = new HashSet<PartnerProduct>();
        }
    
        public int ProductTypeId { get; set; }
        public string Name { get; set; }
        public string ArticleNumber { get; set; }
        public double MinimumCoast { get; set; }
    
        public virtual ICollection<PartnerProduct> PartnerProduct { get; set; }
        public virtual ProductType ProductType { get; set; }
    }
}
